Add project information to pyproject.toml + run tests with python 3.11
matrix-org/vodozemac-bindings pull request #6
Opened 2023-03-26 07:58 UTC by HelgeKrueger

The additional information should improve what is shown on pypi, e.g. https://pypi.org/project/vodozemac/
https://pypi.org/project/vodozemac-python/

Please republish the project to it with this description

2023-03-27 07:25 UTC, poljar requested changes
Left a couple of nits, looks good otherwise.

Please note that I mostly published the bindings to reserve the name, they are still undocumented and some API breakage is planned.

2023-03-27 07:25 UTC, poljar commented on python/pyproject.toml
> +description = "Python bindings for vodozemax"
```suggestion
description = "Python bindings for vodozemac"
```

2023-03-27 07:25 UTC, poljar commented on python/pyproject.toml
> +repository = "https://github.com/matrix-org/vodozemac-bindings"
There's a missing newline.

2023-03-27 08:21 UTC, HelgeKrueger commented
I force pushed the two changes.

2024-09-05 15:17 UTC, poljar commented
This has been included in the new repo: https://github.com/matrix-nio/vodozemac-python/pull/5

2024-09-05 15:17 UTC, closed without merging